config/routes.rb
Rails.application.routes.draw do
  root 'user/posts#index'

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/users/sessions#new_guest'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
    end
    resources :posts, only: [:index, :show, :edit, :destroy]
    resources :genres, only: [:index, :create, :destroy, :edit, :update]
    root 'posts#index'
  end

  namespace :user do
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get :follows, :followers # フォロー、フォロワーページ
        post :destroy, as: 'destroy'
      end
      collection do
        get 'search'
      end
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'search'
        get "following_posts"
      end
    end
    post 'follow/:id' => 'relations#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relations#unfollow', as: 'unfollow' # フォローを外す
    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :favorites, only: [:index] # お気に入り機能
  end

  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    passwords: 'admin/admins/passwords',
    registrations: 'admin/admins/registrations',
  }
  devise_for :users, controllers: {
    sessions: 'user/users/sessions',
    passwords: 'user/users/passwords',
    registrations: 'user/users/registrations',
    omniauth_callbacks: 'user/users/omniauth_callbacks',
  }

  Refile.secret_key = '84d656a3f884f325accbb721f8094ab5f7e7b3408d3f519c17a2093ad98ba62782a3f5d33fa0798131e86476ebdeb5c9c8c170b7ff33f7f61b4c0f59cf0a0506'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(facebook google_oauth2)

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  attachment :image

  def self.search(search)
    return User.all unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    { user: user, sns: sns }
  end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    if user.blank?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
    end
    { user: user }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    { user: user, sns: sns }
  end

  def already_favorited?(post)
    favorites.exists?(post_id: post.id)
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id]) # ユーザ毎の情報を得る
    user.destroy # ユーザ情報を削除（退会）
    redirect_to admin_users_path
  end

  def search
    @user_or_post = params[:option]
    @how_search = params[:choice]
    if @user_or_post == "1"
      @users = User.search(params[:search], @user_or_post, @how_search)
    else
      @posts = Post.search(params[:search], @user_or_post, @how_search)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      redirect_to request.referer
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
   end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorites = Favorite.where(user_id: current_user.id)
  end

  def create
    @post = Post.find(params[:post_id])
    favorite = @post.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    redirect_to request.referer
  end

  private

  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to user_posts_path
    when 1
      redirect_to user_post(@post)
    end
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
      redirect_to "/user/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
   end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))

    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.search(params[:search])
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    category_list = params[:category_list]
    if @post.update_attributes(post_params)
      @post.save
      redirect_to user_post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to user_posts_path
  end

  def search
    @posts = Post.search(params[:search])
  end

  def following_posts
    @posts_all = Post.includes(:user, :favorites)
    @user = User.find(current_user.id)
    @follow_users = @user.following_user
    @posts = @posts_all.where(user_id: @follow_users).order("created_at DESC").page(params[:page]).per(10)
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :genre_id, :tag_list)
  end
end

app/controllers/user/relations_controller.rb
class User::RelationsController < ApplicationController
  before_action :authenticate_user!

  def follow # フォローする
    current_user.follow(params[:id])
    redirect_to request.referer
  end

  def unfollow # フォローを外す
    current_user.unfollow(params[:id])
    redirect_to request.referer
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.following_user
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end

    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?', current_user.id)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/user/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/user/users/confirmations_controller.rb
# frozen_string_literal: true

class User::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to(root_path) && return
  end
end

app/controllers/user/users/passwords_controller.rb
# frozen_string_literal: true

class User::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/users/registrations_controller.rb
# frozen_string_literal: true

class User::Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end
end

app/controllers/user/users/sessions_controller.rb
# frozen_string_literal: true

class User::Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/users/unlocks_controller.rb
# frozen_string_literal: true

class User::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
 end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_user_path(@user)
    else
      render :edit
    end
  end

  # 退会する
  def destroy
    @user = User.find(current_user.id)
    @user.toggle!(:is_cancel)
    reset_session
    redirect_to root_path
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user
  end

  def search
    @users = User.search(params[:search])
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/messages_helper.rb
module User::MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/user/users/_slick.html.erb
<p style="text-align: left; opacity: 50%;"><strong>フォローする人を見つけよう</strong></p>
<div class="slick-box<%= slick_number %>">
	<% users.each do |user| %>
		<%= link_to user_user_path(user), class: "no_decoration link_text" do %>
		<div class="slick_capsule">
			<div class = "slick_body card">
		    	<%= attachment_image_tag user, :image, :fill, 60, 60, fallback: "no_image.jpg", size:"60x60",class: "slick_image" %>
		    	<p><%= user.name %></p>
              <p><% if current_user.following?(user) %>
                <%= button_to 'フォロー中',user_unfollow_path(user.id),method: :post,class:"border btn btn-light btn-sm",data: {confirm: "フォローを外しますか？"}  %>
              <% else %>
                <%= button_to 'フォロー',user_follow_path(user.id),method: :post,class:"btn btn-primary btn-sm" %>
              <% end %>
            </p>
		    </div>
		</div>
	    <% end %>
	<% end %>
</div>

<style>
  .no_decoration{
    text-decoration: none;
  }
.slick_capsule{
  width :200px;
  max-height: 200px;
}

.slick_body {
  height: 200px;
  width: 180px;
  overflow:   hidden;
  position:   relative;
}
.slick_image {
  border-radius: 50%;
  margin-top: 30px;
  margin-left: 60px;
}


</style>

<script type="text/javascript">

$('.slick-box<%= slick_number %>').slick({
    arrows: true,
    autoplay: true,
    slidesToShow: 5,
    slidesToScroll: 2,
});
</script>

app/views/user/users/_users.html.erb
<table class = "table table-borderless" style="table-layout:fixed;">
			<tbody>
				<% users.each do |user| %>
				<tr>
					<td style="width:150px"><%= link_to user_user_path(user) do %>
						<%= attachment_image_tag user, :image,:fill, 60,60, format: "jpeg",fallback:"no_image.jpg",size:"60x60",class: "user_image" %>
						<%= user.name %>
						<% end %>
					</td>

					<td style="width:365px"><%= user.introduction %></td>

					<td style="padding-top: 1rem;"><% if current_user.id != user.id %>
	   						<% if current_user.following?(user) %>
								<%= button_to 'フォロー中',user_unfollow_path(user.id),method: :post,class:"border btn btn-light btn-sm",data: {confirm: "フォローを外しますか？"}  %>
							<% else %>
								<%= button_to 'フォローする',user_follow_path(user.id),method: :post,class:"btn btn-primary btn-sm" %>
							<% end %>
						<% end %>
					</td>
				</tr>
				<% end %>
			</tbody>
</table>

app/views/user/users/edit.html.erb
<div class = "row">
	<div class="col-md-6">
		<%= form_for(@user, url:user_user_path,method: :patch) do |f| %>
		   <div class="form-row mb-4">
			    <div class="col">
			      <div class="custom-file">
			      <%= f.attachment_field :image,class: "custom-file-input" %>
			      <label class="custom-file-label" for="customFile">画像のアップロード</label>
			      </div>
			    </div>
		  </div>


		  <div class="form-row mb-4">
			    <div class="col">
			    	<%= f.label :"自己紹介" %>
			    	<%= f.text_field :introduction, class: "form-control" %>
			    </div>
		  </div>

		  <div class="form-row mb-4">
			    <div class="col">
			    	<%= f.label :"name" %>
			    	<%= f.text_field :name, class: "form-control" %>
			    </div>
		  </div>

		  <div class="actions" style="text-align: right;">
		   	 	<button type="submit" class="btn btn-secondary">編集する</button>
		  </div>

		<% end %>

	</div>
</div>

app/views/user/users/followers.html.erb
<div class="row">
	<div class="col-md-3">
	</div>

	<div class="col-md-7 border" style="background-color: #fff">
		<%= render 'users',users: @users %>
	</div>
</div>

app/views/user/users/follows.html.erb
<div class="row">
	<div class="col-md-3">
	</div>

	<div class="col-md-7 border" style="background-color: #fff">
		<%= render 'users',users: @users %>
	</div>
</div>

app/views/user/users/index.html.erb
<div class = "row">
	<div class="col-md-3">
		<h3 class="fas fa-users m-4">ユーザー一覧</h3>
		<%= form_tag(user_users_path,:method => 'get') do %>
		  <div style="text-align: center;">
		  <%= text_field_tag :search %>
		  <%= submit_tag 'Search', :name => nil ,class:"btn btn-outline-success m-4" %>
		</div>
		<% end %>
	</div>

	<div class="col-md-7 border" style="background-color: #fff">
		<%= render 'users',users: @users %>
	</div>
</div>

app/views/user/users/search.html.erb
<p>検索</p>
<p>ユーザ一覧</p>
<% @users.each do |user| %>
<li>
	<%= attachment_image_tag user, :image,:fill, 60,60, format: "jpeg",fallback:"no_image.jpg"%>
	<%= link_to user.name,user_user_path(user) %>
</li>
<% end %>

app/views/user/users/show.html.erb
<div class="row">
   <div class="col-md-3  m-4 user_profile border" style="height: 19rem;">
	   	<div  style="text-align: center;">
				<%= attachment_image_tag @user, :image,:fill, 70,70, format: "jpeg",fallback:"no_image.jpg",size:"70x70",class: "user_image" %>
			<br />
				<strong><%= @user.name %></strong>
			<br />
				<small><%= @user.introduction %></small>
		</div>
		<div class="mb-2" style="text-align: center;">
			<div class="d-flex align-items-start">
				<div class="p-2">
					<%= link_to new_user_post_path do %>
					  <div class="link_text">
						<small>投稿</small>
						<%= @user.posts.count %>
					</div>
					<% end %>
				</div>
				<div class="p-2">
					<%= link_to follows_user_user_path do %>
					<div class="link_text">
						<small>フォロー</small>
						<%= @user.follower.count %>
					</div>
					<% end %>
				</div>
				<div class="p-2">
					<%= link_to followers_user_user_path do %>
					<div class="link_text">
						<small>フォロワー</small>
						<%= @user.followed.count %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
		<div style="text-align: center">
				<% if current_user.id == @user.id %>
					<%= link_to "プロフィール編集",edit_user_user_path ,class:"btn btn-outline-secondary" %>
				<% end %>

				<% unless @user.id == current_user.id %>
					<div class="mb-2">
						<% if current_user.following?(@user) %>
							<%= button_to 'フォロー中',user_unfollow_path(@user.id),method: :post,class:"border btn btn-light btn-sm",data: {confirm: "フォローを外しますか？"}  %>
						<% else %>
							<%= button_to 'フォローする',user_follow_path(@user.id),method: :post,class:"btn btn-primary btn-sm" %>
						<% end %>
					</div>

					  <% if @isRoom == true %>
					    <%= link_to "DMへGo!", user_room_path(@roomId),class:"btn btn-outline-danger" %>
					  <% else %>
					    <%= form_for @room, url:user_rooms_path ,method: :post do |f| %>

					      <%= fields_for @entry do |e| %>
					        <%= e.hidden_field :user_id, :value=> @user.id %>
					      <% end %>
					      <%= f.submit "DMを始める",class:"btn btn-outline-danger" %>
					    <% end %>
					  <% end %>

				<% end %>
		</div>
	</div>



	<div class="col-md-8" style="padding-top: 2rem;">
		<%= render 'user/posts/posts',posts: @user.posts %>
	</div>
</div>