config/routes.rb
Rails.application.routes.draw do
  root 'user/posts#index'

  post '/homes/guest_sign_in', to: 'homes#new_guest'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/users/sessions#new_guest'
  end

  namespace :admin do
    resources :users, only: [:index, :show, :edit, :update, :destroy] do
      collection do
        get 'search'
      end
    end
    resources :posts, only: [:index, :show, :edit, :destroy]
    resources :genres, only: [:index, :create, :destroy, :edit, :update]
    root 'posts#index'
  end

  namespace :user do
    resources :users, only: [:show, :index, :edit, :update] do
      member do
        get :follows, :followers # フォロー、フォロワーページ
        post :destroy, as: 'destroy'
      end
      collection do
        get 'search'
      end
    end
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
      collection do
        get 'search'
        get "following_posts"
      end
    end
    post 'follow/:id' => 'relations#follow', as: 'follow' # フォローする
    post 'unfollow/:id' => 'relations#unfollow', as: 'unfollow' # フォローを外す
    resources :rooms, only: [:create, :show, :index]
    resources :messages, only: [:create]
    get 'tags/:tag', to: 'posts#index', as: :tag

    resources :favorites, only: [:index] # お気に入り機能
  end

  devise_for :admins, controllers: {
    sessions: 'admin/admins/sessions',
    passwords: 'admin/admins/passwords',
    registrations: 'admin/admins/registrations',
  }
  devise_for :users, controllers: {
    sessions: 'user/users/sessions',
    passwords: 'user/users/passwords',
    registrations: 'user/users/registrations',
    omniauth_callbacks: 'user/users/omniauth_callbacks',
  }

  Refile.secret_key = '84d656a3f884f325accbb721f8094ab5f7e7b3408d3f519c17a2093ad98ba62782a3f5d33fa0798131e86476ebdeb5c9c8c170b7ff33f7f61b4c0f59cf0a0506'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  acts_as_taggable

  attachment :image

  validates :title, presence: true
  validates :image, presence: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    return Post.all unless search
    Post.where(['title LIKE ?', "%#{search}%"])
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i(facebook google_oauth2)

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :sns_credentials, dependent: :destroy

  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :rooms, through: :entries
  attachment :image

  def self.search(search)
    return User.all unless search
    User.where(['name LIKE ?', "%#{search}%"])
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.name = 'ゲスト'
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    { user: user, sns: sns }
  end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    if user.blank?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email,
      )
    end
    { user: user }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    { user: user, sns: sns }
  end

  def already_favorited?(post)
    favorites.exists?(post_id: post.id)
  end

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @posts = Post.search(params[:search])
  end

  def show
    @post = Post.find_by(id: params[:id])
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to admin_posts_path
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update!(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id]) # ユーザ毎の情報を得る
    user.destroy # ユーザ情報を削除（退会）
    redirect_to admin_users_path
  end

  def search
    @user_or_post = params[:option]
    @how_search = params[:choice]
    if @user_or_post == "1"
      @users = User.search(params[:search], @user_or_post, @how_search)
    else
      @posts = Post.search(params[:search], @user_or_post, @how_search)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to request.referer
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if @comment.destroy
      redirect_to request.referer
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
   end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorites = Favorite.where(user_id: current_user.id)
  end

  def create
    @post = Post.find(params[:post_id])
    favorite = @post.favorites.new(user_id: current_user.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: @post.id)
    favorite.destroy
    redirect_to request.referer
  end

  private

  def redirect
    case params[:redirect_id].to_i
    when 0
      redirect_to user_posts_path
    when 1
      redirect_to user_post(@post)
    end
  end
end

app/controllers/user/messages_controller.rb
class User::MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    if Entry.where(:user_id => current_user.id, :room_id => params[:message][:room_id]).present?
      @message = Message.create(params.require(:message).permit(:user_id, :content, :room_id).merge(:user_id => current_user.id))
      redirect_to "/user/rooms/#{@message.room_id}"
    else
      redirect_back(fallback_location: root_path)
    end
   end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @all_ranks = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(5).pluck(:post_id))

    if params[:tag]
      @posts = Post.tagged_with(params[:tag])
    else
      @posts = Post.search(params[:search])
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      redirect_to user_post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    category_list = params[:category_list]
    if @post.update_attributes(post_params)
      @post.save
      redirect_to user_post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    redirect_to user_posts_path
  end

  def search
    @posts = Post.search(params[:search])
  end

  def following_posts
    @posts_all = Post.includes(:user, :favorites)
    @user = User.find(current_user.id)
    @follow_users = @user.following_user
    @posts = @posts_all.where(user_id: @follow_users).order("created_at DESC").page(params[:page]).per(10)
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image, :genre_id, :tag_list)
  end
end

app/controllers/user/relations_controller.rb
class User::RelationsController < ApplicationController
  before_action :authenticate_user!

  def follow # フォローする
    current_user.follow(params[:id])
    redirect_to request.referer
  end

  def unfollow # フォローを外す
    current_user.unfollow(params[:id])
    redirect_to request.referer
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.following_user
  end
end

app/controllers/user/rooms_controller.rb
class User::RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @currentEntries = current_user.entries
    myRoomIds = []

    @currentEntries.each do |entry|
      myRoomIds << entry.room.id
    end

    @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?', current_user.id)
  end

  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/user/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/user/users/confirmations_controller.rb
# frozen_string_literal: true

class User::Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook)
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: "devise/registrations/new"
    end
  end

  def failure
    redirect_to(root_path) && return
  end
end

app/controllers/user/users/passwords_controller.rb
# frozen_string_literal: true

class User::Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/users/registrations_controller.rb
# frozen_string_literal: true

class User::Users::RegistrationsController < Devise::RegistrationsController
  before_action :check_guest, only: :destroy

  def check_guest
    if resource.email == 'guest@example.com'
      redirect_to root_path, alert: 'ゲストユーザーは削除できません。'
    end
  end
end

app/controllers/user/users/sessions_controller.rb
# frozen_string_literal: true

class User::Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: 'ゲストユーザーとしてログインしました。'
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/users/unlocks_controller.rb
# frozen_string_literal: true

class User::Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.search(params[:search])
  end

  def show
    @user = User.find(params[:id])
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
 end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_user_path(@user)
    else
      render :edit
    end
  end

  # 退会する
  def destroy
    @user = User.find(current_user.id)
    @user.toggle!(:is_cancel)
    reset_session
    redirect_to root_path
  end

  def follows
    @user = User.find(params[:id])
    @users = @user.following_user
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.follower_user
  end

  def search
    @users = User.search(params[:search])
  end

  private

  def user_params
    params.require(:user).permit(:name, :image, :introduction)
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/user/posts/_carousel.html.erb
<div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="carousel-item active">
        <%= image_tag'yakigashi_kattan13.jpg',class:"d-block w-100 top_img1" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>First slide label</h3>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
		<%= image_tag'yakigashi_kattan12.jpg',class:"d-block w-100 top_img1" %>
        <div class="carousel-caption d-none d-md-block">
          <h3>Second slide label</h3>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>

app/views/user/posts/_posts.html.erb
<% posts.each do |post| %>
<div class="d-inline-block posts mb-3 mr-4">
	<%= link_to user_post_path(post) do %>
    <div class = "sample3">
    	<div class = "mask">
    	  <div class ="caption">
    	  	<strong>
    	  		<i class="fa fa-heart m-1" style="color: #fff;"><%= post.favorites.count %></i>
    			  <i class="fas fa-comment" style="color: #fff;"><%= post.comments.count %></i>
      		</strong>
      	</div>
      </div>
		  <%= attachment_image_tag post, :image,:fill, 292,292, format: "jpeg" %>


    </div>
	<% end %>
	<p class="mb-0 text-right mr-1" style="line-height: 1rem;">
		<small><strong><%= post.title %></strong></small>
	</p>
</div>

<% end %>

app/views/user/posts/_ranking.html.erb
<p>いいねランキング</p>
<% all_ranks.each.with_index(1) do |post,i| %>
<div class="d-inline-block posts  mr-2">
	<%= link_to user_post_path(post) do %>
	    <div class = "sample3">
	    	<div class = "mask">
	    	    <div class ="caption" style="padding:3rem 3rem 0 0;">
		    	  	<strong>
		    	  		<small>
			    	  		<i class="fa fa-heart" style="color: #fff;"><%= post.favorites.count %></i>
			    			<i class="fas fa-comment" style="color: #fff;"><%= post.comments.count %></i>
			    		</small>
		      		</strong>
	      		</div>
	      </div>
			  <%= attachment_image_tag post, :image,:fill, 200,200, format: "jpeg" %>

	    </div>
	   第<%= i%>位
	<% end %>
</div>
<% end %>

app/views/user/posts/edit.html.erb
<div class="row">
  <div clas="col-md-12">
    <div class="d-flex flex-column">
    <%= form_for(@post, url:user_post_path) do |f| %>
    	<div class="form-row mb-4">
            <div class="col">
              <div class="custom-file">
              <%= f.attachment_field :image,class: "custom-file-input" %>
              <label class="custom-file-label" for="customFile">画像のアップロード</label>
              </div>
            </div>
          </div>

          <div class="form-row mb-4">
            <div class="col">
            	<%= f.label :"タイトル" %>
            	<%= f.text_field :title, class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-4">
            <div class="col">
            	<%= f.label :"本文" %>
            	<%= f.text_area :body,size: "20x10",class: "form-control" %>
            </div>
          </div>

          <div class="form-row mb-5">
            <div class="col">
              <%= f.label "タグ" %>
              <ul id="post-tags"></ul>
              <%= hidden_field_tag :category_hidden,@category_list %>
            </div>
          </div>

          <div class="actions" style="text-align: right;">
        <h4><%= f.submit 'Update Book', class: "btn btn-default" %></h4>
    </div>
    <% end %>
    </div>
  </div>
</div>

app/views/user/posts/following_posts.html.erb
<div class = "row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<h4>タイムライン</h4>
		<% @posts.each do |post| %>
		<table class="table table-borderless">
			<tbody class="card">
				<tr>
					<td><%= link_to user_user_path(post.user) do %>
							<%= attachment_image_tag post.user,:image,:fill, 60,60, format: "jpeg",fallback:"no_image.jpg",size:"60x60",class: "user_image" %>
							<%= post.user.name %>
						<% end %>
					</td>
				</tr>
				<tr>
				<td style="padding: 0;">
					<%= link_to user_post_path(post) do %>
						<%= attachment_image_tag post, :image,:fill, 500,600, format: "jpeg",fallback:"no_image.jpg",size:"600x600" %>
					<% end %>
				</td>
				</tr>
				<tr>
					<td style="padding-bottom: 0;">
						<% if post.favorited_by?(current_user) %>
						    <%= link_to user_post_favorites_path(post), method: :delete, remote: true do %>
							      <h4 class="fas fa-heart text-danger mb-0" aria-hidden="true"></h4>
							<% end %>
						<% else %>
						    <%= link_to user_post_favorites_path(post), method: :post, remote: true do %>
							      <h4 class="far fa-heart mb-0" aria-hidden="true"></h4>
							<% end %>
						<% end %>
					</td>
				</tr>
				<tr>
					<td style="padding-top: 0;"><%= link_to post.title,user_post_path(post) ,class: "link_text"%></td>
				</tr>
				<tr>
					<td style="padding-top: 0;"><small># <%= raw(post.tag_list.map { |t| link_to t, user_tag_path(t) }.join('# ')) %></small></td>
				</tr>
			</tbody>
		</table>
		<% end %>
	</div>

</div>

app/views/user/posts/index.html.erb
<div class="row">


<div class="col-md-12" style="text-align: center;">

	<%= render 'user/users/slick' ,users: @users,slick_number: '1' %>



 <div style="padding-top: 20px">
	<%= render 'posts',posts: @posts %>
 </div>

 <div style="padding-top: 20px">
 	<%= render 'ranking',all_ranks: @all_ranks %>
 </div>
</div>
</div>

app/views/user/posts/new.html.erb
<div class = "row">
  <div class="col-md-6">
    <div class="d-flex flex-column">
    <%= form_for(@post, url: user_posts_path, mehtod: :post) do |f|%>

     <%= render 'layouts/errors', model: f.object %>


      <div class="form-row mb-4">
        <div class="col">
          <div class="custom-file">
          <%= f.attachment_field :image,class: "custom-file-input" %>
          <label class="custom-file-label" for="customFile">画像のアップロード</label>
          </div>
        </div>
      </div>

      <div class="form-row mb-4">
        <div class="col">
        	<%= f.label :"タイトル" %>
        	<%= f.text_field :title, class: "form-control",id: :post_title %>
        </div>
      </div>

      <div class="form-row mb-4">
        <div class="col">
        	<%= f.label :"本文" %>
        	<%= f.text_area :body,size: "20x10",class: "form-control" %>
        </div>
      </div>

      <div class="form-row mb-4">
        <div class="col">
          <%= f.label :"タグ" %>
          <%= f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control" %>
        </div>
      </div>



      <div class="actions" style="text-align: right;">
        <button type="submit" class="btn btn-secondary">投稿する</button>
      </div>

    <% end %>
    </div>

  </div>
</div>

app/views/user/posts/search.html.erb
<p>検索</p>
<% if @user_or_post == "1" %>
　<p>ユーザ一覧</p>
	<% @user.each do |user| %>
	<li>
		<%= attachment_image_tag user, :image,:fill, 60,60, format: "jpeg",fallback:"no_image.jpg"%>
		<%= link_to user.name,user_user_path(user) %>
	</li>
	<% end %>


<% elsif @user_or_post == "2" %>
　<p>投稿一覧</p>
	<ul><% @post.each do |post| %>
	  <li>
	    <%= link_to post.title,user_post_path(post) %>
	    <%= post.created_at %>
	  </li>
	  <%= link_to "編集",edit_user_post_path(post) %>
	  <% end %>
	</ul>

<% end %>

app/views/user/posts/show.html.erb
<div class="row">
	<div class="col-md-3">
	</div>
	<div class="col-md-7">
		<div style="padding-top: 10px;">
			<%= link_to user_user_path(@post.user) do %>
				<div class="link_text">
					<%= attachment_image_tag @post.user, :image,:fill, 60,60, format: "jpeg",fallback:"no_image.jpg",size:"60x60" ,class: "user_image" %>
					<%= @post.user.name %>
				</div>
			<% end %>
		</div>
		<strong style="font-size: 2rem"><%= @post.title %></strong>
		<br />
			<%= attachment_image_tag @post, :image,:fill, 600,700, format: "jpeg",fallback:"no_image.jpg"%>

		<br />
		<h4 style="padding-top: 30px;"><%= @post.body %></h4>

		<td style="text-align: right;"># <%= raw(@post.tag_list.map { |t| link_to t, user_tag_path(t) }.join(' # ')) %></td>
		<br />

	<% if current_user.id == @post.user.id %>
		<div style="text-align: right;">
			<%= link_to "削除",user_post_path(@post),method: :delete %>
			<%= link_to "編集",edit_user_post_path(@post) %>
		</div>
	<% end %>


			<div class="border"></div>
			<div id= "#favorite-<%= @post.id %>">
			<%= render 'user/favorites/favorite',post: @post ,favorites: @favorites %>
			</div>

		<div style = "padding-top: 2rem;"id = "comments_area">
			<%= render 'user/comments/index',post: @post,user: @user,comment: @comment %>
		</div>
			<%= render 'user/comments/form',post: @post,comment: @comment %>
	</div>
</div>


<style>
	.border {
	border: 1px solid;
	}

	.post_body {
		font-size: 2rem;
	}
</style>